#this is the config file for servers

state_backup_folder: ../state_backup

f: 2

x: -1

num_failed_primary: 1

msg_drop_rate: 0

servers_list:
   0:
      host: bigdata.eecs.umich.edu
      port: 50000
   1: 
      host: bigdata.eecs.umich.edu
      port: 50001
   2: 
      host: bigdata.eecs.umich.edu
      port: 50002
   3: 
      host: bigdata.eecs.umich.edu
      port: 50003
   4:
      host: bigdata.eecs.umich.edu
      port: 50004
   5:
      host: bigdata.eecs.umich.edu
      port: 50005



